### ISSUE TITLE
Image doesn't use in-memory database per default

### ISSUE THREAD

**Issue by Sejmou** [tabular-io/iceberg-rest-image#68]
The documentation of this image on [DockerHub](https://hub.docker.com/r/tabulario/iceberg-rest) mentions that it uses an 'in memory backend'. However, I tested it locally and noticed that the catalog was in fact persisted (i.e. it still existed after rebooting the container). I assume this is due to an error in the [source code](https://github.com/tabular-io/iceberg-rest-image/blob/605a118188eb4c325ca0da0e581c5c9ca3ddc9a1/src/main/java/org/apache/iceberg/rest/RESTCatalogServer.java#L68C1-L68C1).

I think the connection string `jdbc:sqlite:file:/tmp/iceberg_rest_mode=memory` in
```java
catalogProperties.putIfAbsent(
        CatalogProperties.URI, "jdbc:sqlite:file:/tmp/iceberg_rest_mode=memory");
```

needs to be replaced. Currently, this creates an `iceberg_rest_mode=memory` file in the `tmp` directory of the container that _is_ persisted and is just a regular `sqlite` DB file.

**Comment by manuzhang** [comment]
From [the README example](https://github.com/tabular-io/iceberg-rest-image?tab=readme-ov-file#browse), this looks to be on purpose, since you can already list namespaces on start.

**Comment by dargmuesli** [comment]
This seems to be fixed in the migration to apache/iceberg: https://github.com/apache/iceberg/pull/10908/files#diff-3e0c3a54cb6a1c1992b7aeaf60aaf8df6457f51f2968ff2311b9b0fd827cb150R71

**Comment by Fokko** [comment]
Kudo's to @danielcweeks 🙌
